### ISSUE TITLE
Implement minimal support for MonStrPub

### ISSUE THREAD

**Issue by ekiru** [kibimon/monstodon#1]
This issue will contain a plan for implementing the minimum stuff needed for an initial implementation of MonStrPub in Mastodon as described at ~https://gist.github.com/marrus-sh/7ec8b80806f7409c4216dede8cb1432e~ <https://monstr.pub/spec>

WIP!!! the implementation plan is still being composed

# Phase 1: Mon, Species, and Trainers
* [x] Merge #3 (see PR for TODO list)

# Phase 2.1: Mon federation

* [ ] Figure out a way of using `include`s to manage serialization of concepts…
    * [ ] `ActivityPub` includes:
        * [ ] Actors
        * [ ] Statuses
        * [ ] Links (mentions; hashtags)
        * [ ] Images
    * [ ] `RPPub` includes:
        * [ ] Classes
        * [ ] Instances
    * [ ] `MonStrPub` includes:
        * [ ] Mon
        * [ ] Trainers
        * [ ] Routes
        * [ ] Species
* [ ] Serialize core object types…
    * [ ] Create a `MonStrPub::ActivityStreams::SpeciesSerializer` serializer for `mon:Species`
    * [ ] Create a `MonStrPub::ActivityStreams::MonSerializer` serializer for `mon:Mon`
    * [ ] Create a `MonStrPub::ActivityStreams::RouteSerializer` serializer for `mon:Route`s
    * [ ] Create a `MonStrPub::ActivityStreams::TrainerSerializer` serializer for `mon:Trainer`s
* [ ] Handle the above in collections…
    * [ ] `ActivityPub::CollectionsController`
    * [ ] `ActivityPub::InboxesController`
    * [ ] `ActivityPub::OutboxesController`
* [ ] Make sure that inboxes/notifications/follows/etc. work normally for all actors
* [ ] Make sure WebFinger requests work for all actors
* [ ] Handle actor types in `ActivityPub::ProcessAccountService` (used by `ActivityPub::FetchRemoteAccountService` and `ActivityPub::Activity::Update`)
* [ ] Make `mon:mon` on `mon:Trainer` a proper collection
  * [ ] Add a reference to the `mon` collection in `MonStrPub::ActivityStreams::TrainerSerializer`
* [ ] Specs for this stuff
  * [ ] Ensure specs handle WebFinger requests for all actor types
  * [ ] Ensure specs handle following/follower collections for all actor types
  * [ ] Ensure specs handle inboxes for all actor types
  * [ ] Ensure specs handle outboxes for all actor types
  * [ ] Add specs for the `mon:mon` collection on `mon:Trainers`

# Phase 2.2: Mon API

* [ ] Expose account type in accounts API
  * Possibly optional, since trainers have `mon` and mon have `mon_data`, but might be good for clarity
* [ ] Expose mon attributes in accounts API
  * [ ] `mon_data` property containing mon data
  * [ ] Mon lookup by `mon_id`
* [ ] Expose trainers attributes in accounts API
  * [ ] `mon` property
  * [ ] Trainer lookup by `trainer_id`
* [ ] Create API endpoints for `Species`
  * [ ] Lookup by `national_dex`, `regional_dex`, `id`
* [ ] Frontend support for mon API
  * [ ] Visually distinguish mon from trainers
  * [ ] Have a mechanism for viewing mon properties
  * [ ] Have a mechanism for viewing a trainer's mon
  * [ ] Have a mechanism for viewing species data
* [ ] Specs for this stuff
  * [ ] Add specs for account type
  * [ ] Add specs for mon properties
  * [ ] Add specs for trainer properties
  * [ ] Add specs for species endpoints and properties

# Phase 3: Regions and routes

TODO plan out

# Phase 4.1: Route federation

TODO plan out

# Phase 4.2: Route API

TODO plan out

# Phase 5: Moves, Use-less Items, and impossible Captures

TODO plan out

# Phase 6: Flesh things out

TODO plan out (this one will fill in the rest of the properties we didn't already cover)

**Comment by marrus-sh** [comment]
#### RE: Phase 4 (currently: Moves, Use-less Items, and impossible Captures)

I'm currently thinking (kibimon/activitymon#8) that I will probably move `Item` support writ large into a separate *optional* specification, so we can hold off on implementing those for now :P
