### ISSUE TITLE
ActivityMon Roadmap

### ISSUE THREAD

**Issue by marrus-sh** [kibimon/monstodon#2]
This issue will continue to be expanded until a minimal useable product is reached.

#### ActivityPub/ActivityMon spec and implementation

- [ ] Implement basic ActivityMon support (#1)
- [x] Further develop the "Route" concept (kibimon/activitymon#4)
    - Routes should be useable for "finding" Mon
    - People should (optionally) be discoverable through Routes
- [x] Develop a "Search" AP activity that can be used to trigger Announces (kibimon/activitymon#5)

####  Frontend

- [ ] Develop initial Monstodon overworld

**Comment by marrus-sh** [comment]
closing this in favour of having issues on [kibimon/activitymon](https://github.com/kibimon/activitymon) instead ^^
